#!/bin/bash
# UARTへの直接書き込みテストスクリプト

echo "=========================================="
echo "UART直接書き込みテスト"
echo "=========================================="
echo ""
echo "このスクリプトは、GDBからUARTDRに直接書き込んで"
echo "QEMUのシリアル出力に文字が表示されるか確認します。"
echo ""
echo "手順:"
echo "1. ターミナル1: ./run-tkernel-qemu.sh"
echo "2. ターミナル2: ./debug-kernel.sh"
echo "3. GDBで以下を実行:"
echo ""
echo "   (gdb) set \$pc = 0x40200000"
echo "   (gdb) set \$sp = 0x4ff00000"
echo "   (gdb) break uart_pl011_putchar"
echo "   (gdb) continue"
echo "   (gdb) print/x \$x0  # 送信する文字"
echo "   (gdb) print/x *(volatile unsigned int*)0x09000030  # UARTCR"
echo "   (gdb) print/x *(volatile unsigned int*)0x09000018  # UARTFR"
echo "   (gdb) finish  # 関数実行完了まで"
echo "   # この時点でQEMUのターミナルを確認"
echo "   (gdb) continue  # 次の文字まで"
echo ""
echo "または、直接書き込みテスト:"
echo "   (gdb) set *(volatile unsigned int*)0x09000000 = 0x48  # 'H'"
echo "   (gdb) set *(volatile unsigned int*)0x09000000 = 0x65  # 'e'"
echo "   (gdb) set *(volatile unsigned int*)0x09000000 = 0x6c  # 'l'"
echo "   (gdb) set *(volatile unsigned int*)0x09000000 = 0x6c  # 'l'"
echo "   (gdb) set *(volatile unsigned int*)0x09000000 = 0x6f  # 'o'"
echo ""

